built ltp: fix type, ar->as
still can't build pass due to:
/srv/work/run-simulator-aarch64/ltp/lib/tst_res.c:204: undefined reference to `pthread_mutex_lock'